name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  types_checking:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Start Supabase local development setup
      - name: Start Supabase local development setup
        run: supabase start

      # Verify generated types are checked in
      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > types/database.types.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet types/database.types.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

  dryrun:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ github.base_ref == 'main' && secrets.PRODUCTION_DB_PASSWORD || secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ github.base_ref == 'main' && secrets.PRODUCTION_PROJECT_ID || secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push --dry-run

  # database-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: supabase/setup-cli@v1
  #       with:
  #         version: latest

  #     # Database test here
  #     - name: Run database tests
  #       run: |
  #         supabase sql --file=path/to/your/database_test.sql
