name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Supabase CLI
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      # Start Supabase local development setup
      - name: Start Supabase local development setup
        run: supabase start

      # Verify generated types are checked in
      - name: Verify generated types are checked in
        run: |
          supabase gen types typescript --local > types.gen.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet types.gen.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi

      # Run database migrations
      - name: Run database migrations
        run: supabase db migrate

