name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x.x
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run lint:types
      - run: exit 1 

  check_lint_result:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Lint conclusion: ${{ needs.lint.conclusion }}"
          echo "Lint result: ${{ needs.lint.result }}"

  deploy_db:
    needs: lint
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PRODUCTION_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push

  stop_cloudflare_deploy:
        needs: lint
        runs-on: ubuntu-latest
      
        steps:
          - name: Stop Cloudflare Deploy on Lint Failure
            if: ${{ needs.lint.result != 'success' }}
            run: |
              curl -X PATCH "https://api.cloudflare.com/client/v4/accounts/2fe55ec2924319fd78ffefd0e3d213ff/pages/projects/test" \
                -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                -H "Content-Type: application/json" \
                --data '{"production_branch": "main"}'

      # - name: Install dependencies
      #   run: npm install

      # - name: Build project
      #   run: npx @cloudflare/next-on-pages@1

  # deploy:
  #       runs-on: ubuntu-latest
  #       permissions:
  #         contents: read
  #         deployments: write
  #       name: Deploy to Cloudflare Pages
  #       steps:
  #         - name: Checkout
  #           uses: actions/checkout@v3
  #         - name: Build
  #           run: npx @cloudflare/next-on-pages@1  # Замените эту команду на вашу команду сборки, если она отличается
  #         - name: Publish
  #           uses: cloudflare/pages-action@v1
  #           with:
  #               apiToken: YjW57VcYBMjfE0PINwCWbqJZqR0jPVSCkrzbrt2w
  #               accountId: 2fe55ec2924319fd78ffefd0e3d213ff
  #               projectName: test
  #               directory: /
  #               gitHubToken: ${{ secrets.CLOUDFLARE_PAGES_GITHUB_TOKEN }}
